[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "code-trainer"
version = "0.0.1"
requires-python = ">=3.9"
readme = "README.md"
description = "Systeme d'entrainement"
dependencies = []

[project.scripts]
trainer = "trainer:main"

[tool.setuptools]
py-modules = ["trainer", "arg", "importBase"]

[tool.setuptools.package-dir]
"" = "src"