[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "code-trainer"
version = "0.0.5"
requires-python = ">=3.9"
readme = "README-PYPI.md"
description = "Systeme d'entrainement"
dependencies = ["PyYAML"]

[project.scripts]
trainer = "trainer:main"

[tool.setuptools]
py-modules = [
	"arg",
	"check",
	"execRun",
	"history",
	"importBase",
	"install",
	"ls",
	"recommend",
	"stats",
	"timer",
	"trainer",
]

[tool.setuptools.package-dir]
"" = "src"